import React from 'react'
import { Container, Col, Row } from 'reactstrap'
import { GiPuzzle } from "react-icons/gi"
import { ImImages } from "react-icons/im"
import { FaCogs } from "react-icons/fa"
import { AiOutlineBulb } from "react-icons/ai"


import { Link } from "react-router-dom"
import './stepsection.css'

const TIP_DATA = [
    {
        title: "Prototyping",
        desc: 'Use Geets to visualize new ideas and implement them quickly without spending extra resources',
        icon: <FaCogs size={20} />,
    },
    {
        title: 'Reusability',
        desc: 'Geets are created with a simple idea to add reusability to 2D assets',
        icon: <GiPuzzle size={20} />,
    },
    {
        title: 'Diversified Imagery',
        desc: 'Geets are created by 2D artists and generated by a simple algorithm resulting in numerous combinations',
        icon: <ImImages size={20} />,
    },
    {
        title: "Ideas Generation",
        desc: 'Use Geets as inspiration for your own ideas',
        icon: <AiOutlineBulb size={20} />,
    },
]


const StepSection = () => {
  return (
    <section className='step__section'>
        <Container>
            <Row>
                <Col lg='12'className='step__item__title'>
                    <h3>About Geet</h3>
                </Col>

                { 
                    TIP_DATA.map((item, index) => (
                
                    <Col lg='3' md='4' sm='6' key={index} className="step__card">
                        <div className="step__item__info">
                              
                            <span>{item.icon}</span>
                            <div className='step__item__content'>
                                <h5>
                                    <Link to='/wallet'>{item.title}</Link>
                                </h5>
                                <p>{item.desc}</p>
                            </div>
                        </div>
                    </Col>
                    ))
                }


            </Row>
        </Container>
    </section>
  )
}

export default StepSection